title: Quick reference sheets
description: A place where I gather quick reference sheets. All sheets uses groupings based on a type of action (e.g., create, extract, update, convert). Lookups are written from the angle of WHAT you want to achieve, and then giving code that describes HOW to achieve that.
remote_theme: pmarsceill/just-the-docs
color_scheme: "dark"
