title: Quick reference sheets
description: A place where I gather quick reference sheets. All sheets uses groupings based on a type of action (e.g., create, extract, update, convert). Lookups are written from the angle of WHAT you want to achieve, and then giving code that describes HOW to achieve that.
footer_content: Copyright &copy; 2023 Niek Den Teuling, distributed under an <a href=https://github.com/niekdt/cheatsheets/tree/main/LICENSE>MIT license</a>. Please submit new code snippets, ideas, or suggestions by creating an <a href=https://github.com/niekdt/cheatsheets/issues>issue</a> or pull request.
theme: just-the-docs
color_scheme: dark
url: https://niekdt.github.io/cheatsheets/
nav_external_links_new_tab: true

callouts:
  warning:
    title: Warning
    color: red
  important:
    title: Important
    color: blue
  note:
    title: Note
    color: purple

kramdown:
  syntax_highlighter_opts:
    block:
      line_numbers: false

back_to_top: true
back_to_top_text: "Back to top"

gh_edit_link: true
gh_edit_link_text: "Edit this page on GitHub"
gh_edit_repository: "https://github.com/niekdt/cheatsheets"
gh_edit_branch: "main"
gh_edit_view_mode: "edit"
